# Generated by Django 5.0.6 on 2024-05-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productline',
            old_name='attrubuteValue_id',
            new_name='attributeValue_id',
        ),
        migrations.AddField(
            model_name='productline',
            name='store_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
