# Generated by Django 5.0.6 on 2024-05-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_attrubutevalue_id_productline_attributevalue_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
