# Generated by Django 5.0.6 on 2024-05-27 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_brand_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_unit', models.IntegerField(default=0)),
                ('threshhold_unit', models.IntegerField(default=10)),
                ('returned_unit', models.IntegerField(default=0)),
                ('productLine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productline')),
            ],
        ),
    ]
