# Generated by Django 5.0.6 on 2024-05-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='available_unit',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='returned_unit',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='threshhold_unit',
            field=models.PositiveBigIntegerField(default=10),
        ),
    ]
