# Generated by Django 5.0.6 on 2024-05-29 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productstock_available_unit_and_more'),
        ('product', '0009_alter_productattribute_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='productLine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.productline'),
        ),
    ]
