# Generated by Django 5.0.6 on 2024-05-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="total_price",
            new_name="sub_price",
        ),
        migrations.AddField(
            model_name="paymentinformation",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("S", "Successful"), ("R", "Refunded")],
                default="Order Received by Restaurant",
                max_length=100,
            ),
        ),
    ]
