# Generated by Django 5.0.6 on 2024-05-28 03:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_paymentinformation_status_order_cart_id_and_more'),
        ('product', '0008_rename_attrubutevalue_id_productline_attributevalue_id_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sub_price',
        ),
        migrations.RemoveField(
            model_name='paymentinformation',
            name='grand_total',
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.address'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='productLine_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productline'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sub_total',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='amount',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Successful'), ('R', 'Refunded'), ('F', 'Failed'), ('C', 'Cancelled')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='order_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.order'),
        ),
    ]
