# Generated by Django 5.0.6 on 2024-05-30 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitem_sub_total_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
