# Generated by Django 5.0.6 on 2024-05-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_paymentinformation_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Successful', 'Successful'), ('Refunded', 'Refunded'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100),
        ),
    ]
